services:
  app:
    container_name: users_sub_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: users_sub_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_sub_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
