spring:
  application:
    name: user_subscriptions
  datasource:
    url: jdbc:postgresql://db:5432/users_sub_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true
    default-schema: public
